apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: red-shopping
data:
  # Database URLs
  PRODUCTS_DB_URL: "postgresql://postgres:postgres@postgres-products:5432/products_db"
  ORDERS_DB_URL: "postgresql://postgres:postgres@postgres-orders:5432/orders_db"
  MONGO_URI: "mongodb://mongodb:27017/users_db"
  
  # Service URLs
  PRODUCT_SERVICE_URL: "http://product-service:8001"
  USER_SERVICE_URL: "http://user-service:8002"
  ORDER_SERVICE_URL: "http://order-service:8003"
  
  # Infrastructure
  REDIS_HOST: "redis"
  RABBITMQ_HOST: "rabbitmq"
  
  # Environment
  NODE_ENV: "development"
  FLASK_ENV: "development"
