apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: red-shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: frontend-ui
        image: red-shopping-frontend-ui:latest
        imagePullPolicy: Never  # Pour Minikube (images locales)
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
  namespace: red-shopping
spec:
  type: NodePort
  selector:
    app: frontend-ui
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300  # Port accessible depuis l'ext√©rieur de Minikube
